# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Examples how to implement Microservices using Apache Pekko"
  homepage: https://pekko.apache.org/
  labels:
    - pekko
  
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: false
