site:
  title: "Apache Pekko Guide"
  url: https://pekko.apache.org/docs/pekko-platform-guide/current
  
content:
  sources:
  - url: git@github.com:apache/incubator-pekko-platform-guide.git
    start-paths:
    - docs-source/docs
    branches: [current]


ui: 
  bundle:
    url: https://lightbend.github.io/antora-supplemental-ui-lightbend-theme/default_ui/lightbend-theme-ui-002-bundle.zip # Update this to pekko UI? 
    snapshot: true
  supplemental_files: ./supplemental_ui

runtime:
  fetch: true

asciidoc:

  attributes:
    # the following two attributes cause review and todo notes to display
    # review: ''
    # todo: ''
    doc-title: 'Apache Pekko Guide'
    # the following turns on next and previous links in the new template
    page-pagination: ""
    page-toctitle: "On This Page"

output:
  dir: ./../target
  clean: true
